language: php
php:
  - 5.6
script: 
  - find . -type f -name *.php | xargs -n1 php -l 
deploy:
     provider: releases
     api_key:
         secure: $GH_TOKEN
     file: 
         - test.php
     skip_cleanup: true
     on:
         repo: https://github.com/rjullien/testTravis-CI.git
   
